"""empty message

Revision ID: 3c3e7b38368a
Revises: 
Create Date: 2016-12-06 12:27:52.637840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3e7b38368a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_info', sa.Column('label', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_info', 'label')
    # ### end Alembic commands ###
